### ISSUE TITLE
Emails cannot be sent out through port 25, can the port be changed to 465

### ISSUE THREAD

**Issue by shadowwider** [Jinnrry/PMail#8]
Oracle has blocked outbound connections over SMTP port 25, but allows SMTP over SSL connections on port 465.

I noticed in the source code that the port can be changed, but I have very limited knowledge about this.

I'm not sure if this project supports sending emails via SMTPS. It would be great if someone could advise if it's possible to configure the application to send emails through port 465 instead of 25. This would allow emails to be delivered successfully.

Any help or pointers are much appreciated!

**Comment by Jinnrry** [comment]
done #21

**Comment by shadowwider** [comment]
Thank you. However, after testing, I still can't send it out.

`[error][2023-09-08 19:24:21][0a00001164fb03e0b1a70fa267939ab0][/Users/didi/privatePjt/PMail/server/smtp_server/send.go:81][0xc0001b6ca0] 邮件投递失败dial tcp 94.23.206.89:25: connect: connection timed out`

The error message recorded is this. From the 2.2.0 source code I reviewed, it first tries to send using port 465 and if that fails, it tries port 25. I tested my machine and it can telnet to the email server's 465 port, but the sending still defaults to port 25. However, the error log for port 25 has overwritten the log for port 465, so I can't see where the error for port 465 is. Is your testing environment working properly?

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.2.1

Please test it with this version and record the output log.

**Comment by Jinnrry** [comment]
Currently, only sending emails with SMTPS protocol ., and it has not yet been implemented for receiving emails.Receiving mail with the SMTPS protocol will probably be implemented in the next version.

**Comment by dachie** [comment]
aliyun亦是如此

**Comment by Jinnrry** [comment]
It has been tested that the SMTP protocol must be used on port 25 for communication between mail servers (e.g. between PMail and Google GMail). Therefore, port 25 is required, and if the server provider does not support it, the server cannot be used as a mail server.
